server:
  port: ${SERVER_PORT:8083}

spring:
  config:
    import: optional:file:${user.dir}/../../.env[.properties]
  application:
    name: user-service
  datasource:
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/vrs_user?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: ${DB_DRIVER:com.mysql.cj.jdbc.Driver}
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

app:
  admin:
    username: ${ADMIN_USERNAME:admin}
    full-name: ${ADMIN_FULL_NAME:System Administrator}
    password: ${ADMIN_PASSWORD:Admin1234}
